### ISSUE TITLE
not worked in heroku

### ISSUE THREAD

**Issue by todokku** [passa1248/ExchangesStream#4]
Hi passa1248,
im deploying this code to heroku but not work correctly :
https://exchangesstream.herokuapp.com/stream/index
waitnig for your response
finest regards
goodbye

**Comment by passa9** [comment]
Hi todokku,
with https protocol you need to change ws to wss

**Comment by todokku** [comment]
how to change it ?
not work without https too : http://exchangesstream.herokuapp.com/stream/index

**Comment by passa9** [comment]
in stream.handlebars file at line 62 change ws to wss.

**Comment by todokku** [comment]
changed it , but problem not solved

**Comment by passa9** [comment]
currently in your site is not changed.

**Comment by todokku** [comment]
see here :
https://taghirtabadolat.herokuapp.com/stream/index
not work !!

**Comment by passa9** [comment]
I opened it now with chrome and it works for me.
